### ISSUE TITLE
Some simple programs fail to compile. simplifyTypes pass raises Fail: ... no varInfo property

### ISSUE THREAD

**Issue by shwestrick** [MPLLang/mpl#107]
## Update (Feb 11, 2020)

The issue appears to have nothing to do with CAS. I updated the title. The error can be triggered just by compiling this:
```
$(SML_LIB)/basis/fork-join.mlb
```

## Old comment

This only happens for certain programs. Many of our benchmarks use CAS without issue.

A minimal (non)working example:

```
$ mpl main.mlb
MLton [mpl] 20200114.142813-ga800070-dirty raised: Fail: x_0 has no varInfo property
```

File `main.sml`:
```
val r = ref 0
val _ =
  if 0 = MLton.Parallel.compareAndSwap r (0, 1)
  then print ("cas succeeded\n")
  else print ("cas failed\n")
```

File `main.mlb`:
```
$(SML_LIB)/basis/basis.mlb
$(SML_LIB)/basis/fork-join.mlb
$(SML_LIB)/basis/mlton.mlb
main.sml
```

**Comment by athas** [comment]
I get a similar error if I try to compile an empty program against fork-join.mlb.  E.g. if I erase the contents of the `fib.sml` example and try to build it, I hit this error.

**Comment by shwestrick** [comment]
## minimal example

I can confirm that even just compiling this is enough to trigger it:
```
$(SML_LIB)/basis/fork-join.mlb
```

## simplifyTypes pass

The error is caused by `simplifyTypes`. **If I disable the simplifyTypes pass, it compiles without issue.**

Here's the error:
```
simplifyTypes raised: Fail: x_2173 has no varInfo property
```
and the relevant code snippet of `main.simplifyTypes.pre.ssa`:
```
...
  block L_1277 (env_291: (t_61) array)
    val x_2174: t_61 = con SOME_17 (x_2163)
    val x_2175: word64 = prim WordS32_extdToWord64 (myId_1)
    val _: unit =
      prim Array_update_noWriteBarrier[t_61] (env_291, x_2175, x_2174)
    val t_59: time_1 = #1 (x_2164)
    val p_1: word32 = #0 (x_2164)
    val x_2173: (word32, word32, time_1) tuple =
      (p_1, global_556 (*0x100:w32*), t_59)
    case tickTimer_2 of
      Env_523 => L_1278
  block L_1278 (env_292:
                  (lambdas_478, lambdas_506, (time_1) array, lambdas_510) tuple)
    call L_1601 (tickTimer_0 (env_292, x_2173)) handle _ => raise
...
```

I've confirmed so far that this section of the program is unchanged through passes `useless`, `removeUnused2`, and `duplicateGlobals2`. On the `splitTypes2` pass, some renaming of types occurs, but the structure is the same.

@MatthewFluet  Any ideas? The presence of `Array_update_noWriteBarrier` seems suspicious since this would be a difference between MPL and MLton. But in this stage of the compiler, all passes treat this prim identically to a normal `Array_update`.

**Comment by shwestrick** [comment]
The example in #109 also shows that the error is only present when the fork-join primitives are not used in the program. So perhaps this is related to dead-code analysis of scheduler code?

Actually, I know for sure that the code snippet from the `simplifyTypes` pass above is scheduler code. Here's some relevant scheduler code. These functions are used to keep track of how much time each scheduler thread spends idle. The interesting function is `stopTimer` which calls `tickTimer` with a 3-tuple. This tuple is (without a doubt) the offending `x_2173` from the snippet above. E.g. notice the use of the global, which is definitely `timerGrain`.
```
  val timerGrain = 256
  fun startTimer myId = (myId, 0, Time.now ())
  fun tickTimer (p, count, t) =
    if count < timerGrain then (p, count+1, t) else
    let
      val t' = Time.now ()
      val diff = Time.- (t', t)
      val _ = updateIdleTime (p, diff)
    in
      (p, 0, t')
    end
  fun stopTimer (p, _, t) =
    (tickTimer (p, timerGrain, t); ())
```

**Comment by MatthewFluet** [comment]
@shwestrick The Basis Library is treated somewhat more aggressively for dead code than other user code.  See `./mlton/core-ml/dead-code.fun` and http://mlton.org/DeadCode.  But, while erroneously discarding side-effecting code might result in a dynamic runtime error, it shouldn't result in a compile-time error.

**Comment by shwestrick** [comment]
> @shwestrick The Basis Library is treated somewhat more aggressively for dead code than other user code. See `./mlton/core-ml/dead-code.fun` and http://mlton.org/DeadCode. But, while erroneously discarding side-effecting code might result in a dynamic runtime error, it shouldn't result in a compile-time error.

I looked into this but it doesn't appear to be a problem with the CoreML dead code pass. The scheduler has it's own .mlb that has no `deadCode true` annotations. Also I tried compiling with `-disable-ann deadCode` and the problem still persists.

**Comment by MatthewFluet** [comment]
What must be happening is that a statement earlier that block is determined to be dead code (e.g., by attempting to use a value whose type has cardinality zero), which causes the processing of the block to abort without processing the rest of the statements.  By not visiting the definition point of the x_2173 variable, its varInfo is not set.  We fixed a related bug in MLton (https://github.com/MLton/mlton/commit/19b07c03fc2c759367be33d39093da37a81f1fa8, in Nov. 2018, so it has been merged into mpl), but this seems to be related to the comments at the end of that commit message.

In this particular program, variable x_2163 is determined to be of a type with cardinality Zero.  Indeed, it appears to be a closure type, but there are no uses of its Env_NNN constructors.

**Comment by shwestrick** [comment]
In regards to the comment at the bottom of that commit (MLton/mlton@19b07c0)

> It is not clear that the treatment of unreachable code following the
construction of a `Zero` cardinality ConApp is sufficiently
robust (because of the DFS that will visit successor blocks), but has
not seemed to be problematic.

Perhaps we've found an example showing that this treatment is not correct in general? Since we clearly have a successor block that is only reachable through an "unreachable" code path.

Here's one possible fix: just propagate uselessness? I.e. sweep through the rest of the block, simplifying all set variables to type unit. So, we still manage to "delete" the block, and all occurrences of those variables (in later blocks) will be seen as useless and handled correctly. Thoughts?

**Comment by MatthewFluet** [comment]
This may also have something to due with the fact that the task queues are registered with the runtime.  For MPL, there is special support for allowing datatypes to participate in FFI.  However, this leads to some complications, because we sometimes want to be conservative about what happens to data exits the program via FFI and sometimes we can assume that nothing extra is happening.

**Comment by MatthewFluet** [comment]
A more robust approach to propagating uselessness would be to use finer grain control on the DFS (or dominator tree) walk.  After encountering a dead block, stop traversing the children blocks (which will necessarily also be dead).  It might be easier with the dominator tree, because with a DFS, just because a block isn't reachable by the first DFS path, it might be reachable by a different path.  But, the `SSATree.Function.dfs` function doesn't give you that fine grained control.  On the other hand, with the dominator tree, all children of a dead block are necessarily dead.

**Comment by MatthewFluet** [comment]
Some more observations:
 * Disabling splitTypes2 (but leaving simplifyTypes enabled) does not exhibit the error.
 * Introducing a removeUnused pass between splitTypes2 and simplifyTypes does not exhibit the error.

From MLton/mlton@f73965085cf85828ca6117d81f8574167aeaabfd:  `SplitTypes` performs a unification-based analysis to split a datatype into distinct instances for constructed values that are not unified.  Because datatypes are recursive, other analyses often conflate all defs and uses of `ConApp`-s; `SplitTypes` allows non-unified instances of a datatype to be analyzed separately.

`simplifyTypes` is exactly one of the other optimization that conflates the information from all defs and uses of a `ConApp`.  So, without `splitTypes2`, the type of `x_2163` isn't a type with cardinality Zero, due to the behavior of the type in other, disjoint parts of the program.  And with an intervening `removeUsed` pass, the type of `x_2163` is also observed to be uninhabited, with a more aggressive dead code elimination.

I really think that a dominator-based transformation would be appropriate.  Note, in particular, that since the type of `x_2163` has cardinality Zero, all code with `x_2163` in scope should be dead code; hence, we should actually cut off transforming the dominator tree when `x_2163` comes into scope.

**Comment by shwestrick** [comment]
That makes sense to me. I'll try the dominator-tree approach today.

**Comment by MatthewFluet** [comment]
O.k.  I was going to take a crack at it as well, since I'll want to apply the fix to upstream MLton as well.  But, I won't get to it until this evening at the earliest.

**Comment by shwestrick** [comment]
Here's what I came up with: shwestrick/mpl@dfdb2fe636b1405a77a2fa8ef0fef78389d68d96

I'm still in the process of testing but it seems to be working. The compilation error is gone and I haven't identified any correctness issues yet.

**Comment by MatthewFluet** [comment]
That's a good minimal approach.  I'm working on something a little more aggressive; mark the code as dead as soon as a variable with an uninhabited type is brought into scope.  In the example above, the block that brings `x_2163` into scope (as a formal) is the first unreachable block (which dominates `L_2177` and many others), so can be dropped.

**Comment by shwestrick** [comment]
Nice, that sounds like a good fix. I'm looking forward to seeing it when you're done.

**Comment by MatthewFluet** [comment]
Here's a more substantial reworking of `SimplifyTypes`: https://github.com/MPLLang/mpl/compare/master...MatthewFluet:mpl-simplify-types-fix

**Comment by shwestrick** [comment]
I did some testing today and it seems to work great. Thanks Matthew!

**Comment by MatthewFluet** [comment]
Unfortunately, I realized today that I was over overzealous with my "simplifying" of `SimplifyTypes`.  I also ended up eliminating the aspects of the transformation that cleaned up types of cardinality 1; such types are equivalent (and many become translated) to unit and can be removed from types, arguments, etc.  Later classes probably clean up most of it, but I'll restore that functionality in the next day or so.
