### ISSUE TITLE
Impossible to use 2-cores implicitly

### ISSUE THREAD

**Issue by EmptyStackExn** [MPLLang/mpl#116]
Hello, I tried to use MPL for a few days but it seems that even if I use `ForkJoin.par`, the compiled program somehow refuses to perform calculation on 2 cores at the same time. I have the impression that computation is done on one thread then on another...

Here is attached a small program describing the kind of computation I need to parallelize. I read the paper from POPL'2020 to understand where this could be related but still I cannot see (maybe usage of lists ?) 🤔 Maybe you have an idea. Best,

[two_lists.zip](https://github.com/MPLLang/mpl/files/4281197/two_lists.zip)

**Comment by shwestrick** [comment]
I gave it a run, and I usually see approximately a 50% speedup on 2 cores, but not always. Occasionally I see a 2-core time that is about the same as the 1-core time.

I believe this is due to a lack of parallelism. In general, to ensure good load balancing, it's important to have much more parallelism than you have processors. Also, for MPL specifically, the design of the GC benefits significantly from parallelism.

When I modify your code to be 4-way parallel and then run it on 2 processors, I consistently see a decent speedup:
```
$ ./two_lists @mpl procs 2 --
Generating dataset...
Performing calculation...
-> [1-core] Time: 1.234 s
-> [Parallel] Time: 0.743 s
```

Here's how I modified the parallel part of your code:
```
val (l0_l, l0_r) = partition l0
val (a, b) = partition l0_l
val (c, d) = partition l0_r
val start_time = Time.now()
val ((a', b'), (c', d')) =
  ForkJoin.par (
    fn _ => ForkJoin.par (fn _ => compute a, fn _ => compute b),
    fn _ => ForkJoin.par (fn _ => compute c, fn _ => compute d)
  )
val end_time = Time.now()
val l1 = a' @ b' @ c' @ d'
val _ = print ("-> [Parallel] Time: " ^ Time.toString (Time.- (end_time, start_time)) ^ " s\n")
```

**Comment by EmptyStackExn** [comment]
Okay, now I see a real difference :ok_hand: Then in this case, is it possible to have command-line arguments to match with `@mpl`-args ? For instance, if I write something like:
```
./a.out --procs [n]
```
would be executed as
```
./a.out @mpl procs [n] --
```
Best regards,

**Comment by shwestrick** [comment]
At the moment we don't have that functionality, but it would be quite nice. I'll add it to the wishlist!
