### ISSUE TITLE
How to disable overflow checks for integers?

### ISSUE THREAD

**Issue by ckoparkar** [MPLLang/mpl#138]
I seem to have forgotten how to do this. I thought I had disabled it with `-default-type int64 -cc-opt -DINT_NO_CHECK`, but that's not it.

**Comment by shwestrick** [comment]
Oh, interesting. I think MLton used to have a `-detect-overflow false` option but it was removed years ago. @MatthewFluet is there a command-line option for this?

**Comment by shwestrick** [comment]
@ckoparkar an alternative: note that in SML, when overflow is desired, the `Word` type can be used instead. Words are unsigned, so overflow is well-defined, similar to how C does it.

```
val x = valOf Int.maxInt
val y = (Word.fromInt x) + 0w1
val z = Word.toIntX y
```

When doing this sort of thing though I'd recommend taking a close look at the documentation, for relative sizes of integers and words. You need to make sure the word bit-width is at least as wide as the integer bit-width.

**Comment by ckoparkar** [comment]
@shwestrick  Yeah, `-detect-overflow false` doesn't seem to exist anymore. Yesterday I found `Primitive.Controls.detectOverflow` which can be controlled using a `-const detectOverflow` flag (?), but I don't think I'm using it correctly. If I print the value of `Primitive.Controls.detectOverflow`, it's always false no matter the flag. 

re:`Word` Thanks! I did not know about this. Actually, more than wanting a well-defined overflow behavior, I'm after a "overflow, don't care" behavior, mostly for benchmarking purposes. I have an old benchmark run where `sequentialFib(48)` took around 37s, and it has now gone up to around 45s. I think I'm unfairly penalizing MLton by not disabling these overflow checks.

**Comment by MatthewFluet** [comment]
Yes, you would control the overflow detection with the `-const` command-line argument.  Admittedly, it is a slightly weird syntax:
```
$ mlton -const "MLton.detectOverflow false"
```
Note the double quotes, because it is a single argument with a space between the name and the value.

Using `Word` is generally better, since it is possible for the correctness of a program to depend on trapping overflow.  In most places in the Basis Library where this matters (e.g., the implementation of `IntInf`), we do use "always overflow checking" primitive (i.e., ones that don't depend on `MLton.detectOverflow`), but that isn't always true of 3-rd party libraries.

**Comment by ckoparkar** [comment]
I see. I'm using `-default-type -int64`. I don't know, maybe the difference in `seqfib`'s performance isn't directly related to overflows. Its the first thing that came to my mind because I was fiddling with overflow checking back then. And I can't tell what else might have changed between now and then. I'll look at this some more.

@shwestrick @MatthewFluet Thanks for the help! I'll go ahead and close this issue for now.
